'use strict';

function getGlyphEntity (glyph) {
  if (glyph) {
    return {
      id:     'foo',
      offset: 0,
      value:  {
        Glyph:       glyph,
        Name:        'Glyph ' + glyph,
        Description: 'Generated by electrum-dev'
      }};
  } else {
    return null;
  }
}

function getGlyphEntities (glyphs) {
  if (glyphs) {
    var array = [];
    glyphs.forEach (g => {
      array.push (getGlyphEntity (g));
    });
    return array;
  } else {
    return null;
  }
}

function getTrips () {
  return {
    a: {
      Pick:
      {
        Time: '10.05',
        Description: 'Mecano SA',
      },
      Drop:
      {
        Time: '11:15',
        Description: 'Fiduciaire Kdo',
      },
      Count: '1x',
      Weight: '0.2 kg',
      Price: '30.00',
    },
    b: {
      Pick:
      {
        Time: '10.45',
        Description: 'Migros Pont-Neuf',
      },
      Drop:
      {
        Time: '13:30',
        Description: 'Mercier P.',
        Glyphs: getGlyphEntities (['warning']),
      },
      Count: '2x',
      Weight: '3.6 kg',
      Price: '45.00',
    },
    c: {
      Pick:
      {
        Time: '11:00',
        Description: 'Coop St. Laurent',
      },
      Drop:
      {
        Time: '14:00',
        Description: 'Dupond J.',
        Glyphs: getGlyphEntities (['bookmark-base']),
      },
      Count: '1x',
      Weight: '0.7 kg',
      Price: '30.00',
    },
    d: {
      Pick:
      {
        Time: '11:15',
        Description: 'Tagada AG',
        Glyphs: getGlyphEntities (['bookmark-secondary', 'bookmark-primary']),
      },
      Drop:
      {
        Time: '16:00',
        Description: 'Micro SA',
      },
      Count: '3x',
      Weight: '1.3 kg',
      Price: '100.00',
      PriceGlyphs: getGlyphEntities (['warning']),
    },
    e: {
      Pick:
      {
        Time: '11:20',
        Description: 'Migros Pont-Neuf',
      },
      Drop:
      {
        Time: '13:00',
        Description: 'Durand W.',
      },
      Count: '1x',
      Weight: '2.5 kg',
      Price: '80.00',
      PriceGlyphs: getGlyphEntities (['bookmark-primary']),
    },
    f: {
      Pick:
      {
        Time: '11:40',
        Description: 'Me Blatide & Associés',
      },
      Drop:
      {
        Time: '15:00',
        Description: 'Fiduciaire du Léman',
      },
      Count: '2x',
      Weight: '1.9 kg',
      Price: '100.00',
    },
    g: {
      Pick:
      {
        Time: '11:45',
        Description: 'Coop St. Laurent',
        Glyphs: getGlyphEntities (['bookmark-primary']),
      },
      Drop:
      {
        Time: '13:30',
        Description: 'Arnaud K.',
        Glyphs: getGlyphEntities (['bookmark-secondary']),
      },
      Count: '1x',
      Weight: '2.5 kg',
      Price: '100.00',
      PriceGlyphs: getGlyphEntities (['warning']),
    },
    h: {
      Pick:
      {
        Time: '13:30',
        Description: 'Fiduciaire du Léman',
      },
      Drop:
      {
        Time: '14:15',
        Description: 'Me Blatide',
      },
      Count: '1x',
      Weight: '0.3 kg',
      Price: '50.00',
    },
    i: {
      Pick:
      {
        Time: '13:30',
        Description: 'Jolibourg SA',
      },
      Drop:
      {
        Time: '14:25',
        Description: 'Aux belles fleurs du Rivage',
        Glyphs: getGlyphEntities (['bookmark-secondary', 'bookmark-base', 'bookmark-primary']),
      },
      Count: '5x',
      Weight: '16.3 kg',
      Price: '182.00',
    },
    j: {
      Pick:
      {
        Time: '13:40',
        Description: 'Kalindo SA',
        Glyphs: getGlyphEntities (['bookmark-secondary', 'bookmark-primary']),
        PriceGlyphs: getGlyphEntities (['warning']),
      },
      Drop:
      {
        Time: '16:05',
        Description: 'Verra G.',
        Glyphs: getGlyphEntities (['bookmark-secondary', 'bookmark-base', 'bookmark-primary']),
      },
      Count: '1x',
      Weight: '1.1 kg',
      Price: '24.00',
    },
    k: {
      Pick:
      {
        Time: '13:55',
        Description: 'Migros La Sallaz',
        Glyphs: getGlyphEntities (['bookmark-secondary']),
      },
      Drop:
      {
        Time: '14:20',
        Description: 'Henry P.',
      },
      Count: '2x',
      Weight: '4.3 kg',
      Price: '110.00',
      PriceGlyphs: getGlyphEntities (['warning']),
    },
    l: {
      Pick:
      {
        Time: '14:15',
        Description: 'Migros La Sallaz',
      },
      Drop:
      {
        Time: '15:00',
        Description: 'Schmidt A.',
        Glyphs: getGlyphEntities (['bookmark-secondary', 'bookmark-primary', 'warning']),
      },
      Count: '1x',
      Weight: '1.8 kg',
      Price: '70.00',
    },
    m: {
      Pick:
      {
        Time: '15:00',
        Description: 'Aux belles fleurs',
        Glyphs: getGlyphEntities (['warning']),
      },
      Drop:
      {
        Time: '16:10',
        Description: 'Ducommun S.',
      },
      Count: '4x',
      Weight: '1.8 kg',
      Price: '100.00',
    },
    n: {
      Pick:
      {
        Time: '15:45',
        Description: 'Fiduciaire Blamond',
      },
      Drop:
      {
        Time: '16:00',
        Description: 'Consulat Belge',
      },
      Count: '1x',
      Weight: '0.3 kg',
      Price: '30.00',
    },
    o: {
      Pick:
      {
        Time: '16:10',
        Description: 'Vermont & Frères',
      },
      Drop:
      {
        Time: '17:00',
        Description: 'Mecano sA',
        Glyphs: getGlyphEntities (['bookmark-primary']),
      },
      Count: '2x',
      Weight: '1.5 kg',
      Price: '70.00',
      PriceGlyphs: getGlyphEntities (['warning']),
    },
    p: {
      Pick:
      {
        Time: '16:15',
        Description: 'Blibli SA',
      },
      Drop:
      {
        Time: '17:15',
        Description: 'Librairie Frankin',
        Glyphs: getGlyphEntities (['bookmark-base']),
      },
      Count: '1x',
      Weight: '2.9 kg',
      Price: '125.00',
      Glyphs: getGlyphEntities (['bookmark-secondary', 'bookmark-primary']),
    },
    q: {
      Pick:
      {
        Time: '16:25',
        Description: 'Blibli SA',
      },
      Drop:
      {
        Time: '17:00',
        Description: 'Librairie Mercier',
      },
      Count: '2x',
      Weight: '5.2 kg',
      Price: '125.00',
      Glyphs: getGlyphEntities (['bookmark-base']),
    },
    r: {
      Pick:
      {
        Time: '16:30',
        Description: 'Coop St. Laurent',
        Glyphs: getGlyphEntities (['bookmark-primary', 'bookmark-base']),
      },
      Drop:
      {
        Time: '17:15',
        Description: 'Coppet F.',
      },
      Count: '1x',
      Weight: '2.0 kg',
      Price: '25.00',
      Glyphs: getGlyphEntities (['warning']),
    },
    s1: {
      Pick:
      {
        Time: '16:35',
        Description: 'Me Georges-André',
      },
      Drop:
      {
        Time: '17:25',
        Description: 'Gare Lausanne',
        Glyphs: getGlyphEntities (['bookmark-base']),
      },
      Count: '3x',
      Weight: '4.7 kg',
      Price: '75.00',
    },
    s2: {
      Pick:
      {
        Time: '17:25',
        Description: 'Gare Lausanne',
        Glyphs: getGlyphEntities (['bookmark-base']),
      },
      Drop:
      {
        Time: '17:45',
        Description: 'Mecano SA',
      },
      Count: '3x',
      Weight: '4.7 kg',
      Price: '75.00',
      Glyphs: getGlyphEntities (['bookmark-secondary', 'bookmark-primary']),
    },
    t: {
      Pick:
      {
        Time: '16:35',
        Description: 'Librairie Bédé',
        Glyphs: getGlyphEntities (['bookmark-base', 'bookmark-primary', 'bookmark-secondary']),
      },
      Drop:
      {
        Time: '17:10',
        Description: 'Blibli SA',
        Glyphs: getGlyphEntities (['warning']),
      },
      Count: '1x',
      Weight: '3.9 kg',
      Price: '120.00',
    },
  };
}

/******************************************************************************/

module.exports = {
  getTrips,
};
